name: hardhat
on: [push]

jobs:
  hardhat-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-versions: "14"
      - run: npm install
      - run: npx hardhat test --network hardhat
